// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package db

import (
	"context"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
    title,
    code,
    credit,
    capacity
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, title, code, credit, capacity, created_at, updated_at
`

type CreateCourseParams struct {
	Title    string `json:"title"`
	Code     string `json:"code"`
	Credit   int32  `json:"credit"`
	Capacity int32  `json:"capacity"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.Title,
		arg.Code,
		arg.Credit,
		arg.Capacity,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.Credit,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses
WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCourse, id)
	return err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, title, code, credit, capacity, created_at, updated_at
FROM courses
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCourseByID(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.Credit,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, title, code, credit, capacity, created_at, updated_at
FROM courses
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCoursesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Code,
			&i.Credit,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET
    title = $2,
    code = $3,
    credit = $4,
    capacity = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, code, credit, capacity, created_at, updated_at
`

type UpdateCourseParams struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	Code     string `json:"code"`
	Credit   int32  `json:"credit"`
	Capacity int32  `json:"capacity"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Title,
		arg.Code,
		arg.Credit,
		arg.Capacity,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.Credit,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
