// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEnrollmentsByCourse = `-- name: CountEnrollmentsByCourse :one
SELECT COUNT(*) FROM enrollments WHERE course_id = $1
`

func (q *Queries) CountEnrollmentsByCourse(ctx context.Context, courseID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEnrollmentsByCourse, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enrollStudent = `-- name: EnrollStudent :one
INSERT INTO enrollments (
    student_id,
    course_id
) VALUES (
    $1, $2
)
RETURNING id, student_id, course_id, enrolled_at
`

type EnrollStudentParams struct {
	StudentID int64 `json:"student_id"`
	CourseID  int64 `json:"course_id"`
}

type EnrollStudentRow struct {
	ID         int64            `json:"id"`
	StudentID  int64            `json:"student_id"`
	CourseID   int64            `json:"course_id"`
	EnrolledAt pgtype.Timestamp `json:"enrolled_at"`
}

func (q *Queries) EnrollStudent(ctx context.Context, arg EnrollStudentParams) (EnrollStudentRow, error) {
	row := q.db.QueryRow(ctx, enrollStudent, arg.StudentID, arg.CourseID)
	var i EnrollStudentRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.EnrolledAt,
	)
	return i, err
}

const listCoursesByStudent = `-- name: ListCoursesByStudent :many
SELECT c.id, c.title, c.code, c.credit, c.capacity, c.created_at, c.updated_at
FROM courses c
JOIN enrollments e ON e.course_id = c.id
WHERE e.student_id = $1
`

func (q *Queries) ListCoursesByStudent(ctx context.Context, studentID int64) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Code,
			&i.Credit,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByCourse = `-- name: ListStudentsByCourse :many
SELECT s.id, s.full_name, s.department, s.status, s.created_at
FROM students s
JOIN enrollments e ON e.student_id = s.id
WHERE e.course_id = $1
`

type ListStudentsByCourseRow struct {
	ID         int64            `json:"id"`
	FullName   string           `json:"full_name"`
	Department string           `json:"department"`
	Status     string           `json:"status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListStudentsByCourse(ctx context.Context, courseID int64) ([]ListStudentsByCourseRow, error) {
	rows, err := q.db.Query(ctx, listStudentsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentsByCourseRow
	for rows.Next() {
		var i ListStudentsByCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Department,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unenrollStudent = `-- name: UnenrollStudent :exec
DELETE FROM enrollments
WHERE student_id = $1 AND course_id = $2
`

type UnenrollStudentParams struct {
	StudentID int64 `json:"student_id"`
	CourseID  int64 `json:"course_id"`
}

func (q *Queries) UnenrollStudent(ctx context.Context, arg UnenrollStudentParams) error {
	_, err := q.db.Exec(ctx, unenrollStudent, arg.StudentID, arg.CourseID)
	return err
}
