// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Course struct {
	ID        int64            `json:"id"`
	Title     string           `json:"title"`
	Code      string           `json:"code"`
	Credit    int32            `json:"credit"`
	Capacity  int32            `json:"capacity"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Enrollment struct {
	ID         int64            `json:"id"`
	StudentID  int64            `json:"student_id"`
	CourseID   int64            `json:"course_id"`
	Grade      pgtype.Text      `json:"grade"`
	EnrolledAt pgtype.Timestamp `json:"enrolled_at"`
}

type RefreshToken struct {
	ID        int64            `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Revoked   bool             `json:"revoked"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Student struct {
	ID          int64            `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	FullName    string           `json:"full_name"`
	DateOfBirth pgtype.Date      `json:"date_of_birth"`
	Department  string           `json:"department"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	IsActive     bool             `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
