// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteCourse(ctx context.Context, id int64) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteStudent(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	EnrollStudent(ctx context.Context, arg EnrollStudentParams) (EnrollStudentRow, error)
	GetCourseByID(ctx context.Context, id int64) (Course, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetStudentByID(ctx context.Context, id int64) (Student, error)
	GetStudentByUserID(ctx context.Context, userID pgtype.UUID) (Student, error)
	GetStudentsByDepartment(ctx context.Context, arg GetStudentsByDepartmentParams) ([]Student, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error)
	ListCoursesByStudent(ctx context.Context, studentID int64) ([]Course, error)
	ListStudents(ctx context.Context, arg ListStudentsParams) ([]Student, error)
	ListStudentsByCourse(ctx context.Context, courseID int64) ([]ListStudentsByCourseRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	RevokeRefreshToken(ctx context.Context, token string) error
	UnenrollStudent(ctx context.Context, arg UnenrollStudentParams) error
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error)
}

var _ Querier = (*Queries)(nil)
