// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStudents = `-- name: CountStudents :one
SELECT COUNT(*) FROM students
`

func (q *Queries) CountStudents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStudents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (
    user_id,
    full_name,
    date_of_birth,
    department,
    status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, full_name, date_of_birth, department, status, created_at, updated_at
`

type CreateStudentParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	FullName    string      `json:"full_name"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Department  string      `json:"department"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.UserID,
		arg.FullName,
		arg.DateOfBirth,
		arg.Department,
		arg.Status,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Department,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM students
WHERE id = $1
`

func (q *Queries) DeleteStudent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteStudent, id)
	return err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, user_id, full_name, date_of_birth, department, status, created_at, updated_at
FROM students
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetStudentByID(ctx context.Context, id int64) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Department,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByUserID = `-- name: GetStudentByUserID :one
SELECT id, user_id, full_name, date_of_birth, department, status, created_at, updated_at
FROM students
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetStudentByUserID(ctx context.Context, userID pgtype.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByUserID, userID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Department,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentsByDepartment = `-- name: GetStudentsByDepartment :many
SELECT id, user_id, full_name, date_of_birth, department, status, created_at, updated_at
FROM students
WHERE department = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetStudentsByDepartmentParams struct {
	Department string `json:"department"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) GetStudentsByDepartment(ctx context.Context, arg GetStudentsByDepartmentParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, getStudentsByDepartment, arg.Department, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.DateOfBirth,
			&i.Department,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many
SELECT id, user_id, full_name, date_of_birth, department, status, created_at, updated_at
FROM students
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListStudentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.DateOfBirth,
			&i.Department,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students
SET
    full_name = $2,
    date_of_birth = $3,
    department = $4,
    status = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, full_name, date_of_birth, department, status, created_at, updated_at
`

type UpdateStudentParams struct {
	ID          int64       `json:"id"`
	FullName    string      `json:"full_name"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Department  string      `json:"department"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.ID,
		arg.FullName,
		arg.DateOfBirth,
		arg.Department,
		arg.Status,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Department,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
